name: my-job

on: push

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: copying code
        uses: actions/checkout@v4

      - name: installing node
        uses: actions/setup-node@v4
        with: 
          node-version: 24.12.0
        
      - name: check node version
        run : node --version
          

